// What may be sent, what may be stored, and nothing else.
//
// One file, imported by the browser that sends an event, the Worker that stores
// it, the export that reads it back and the tests that police all three. A
// schema written twice is a schema that disagrees with itself, and the thing it
// would disagree about here is which fields of a reader end up in a database.
//
// The rule is a closed list, not a filter. An unknown field is rejected rather
// than dropped, so a field somebody adds to the client by accident turns into a
// 400 in development instead of a column of personal data in production. There
// is deliberately nowhere in this file to put an IP, a user-agent, a referrer
// or an email: they are not on the list, so they cannot arrive.

/** The three things a reader can do that the ranker learns from. */
export const EVENT_TYPES = Object.freeze(["impression", "click", "save"]);

/**
 * Which ordering put a row where it is. "none" is for an interaction that is
 * not about a single ranked row: the calendar feed covers the whole region, so
 * subscribing to it is not a vote for the event at the top.
 */
export const RANKING_LABELS = Object.freeze(["production", "candidate", "none"]);

/**
 * Where a row came from. Only "web" is organic, and the evaluator counts only
 * organic rows towards the promotion gate.
 *
 * - web: an ordinary visitor to the deployed board.
 * - dev: localhost, a .local host, or a workers.dev preview. That is us.
 * - synthetic: generated by scripts/recommender-synthesize-events.mjs. Never a
 *   measurement of anything, only a way to exercise the pipeline at zero traffic.
 * - seeded: hand-written rows, for example a fixture in a test.
 * - replay: rows re-emitted from an earlier export.
 */
export const SOURCES = Object.freeze(["web", "dev", "synthetic", "seeded", "replay"]);

/** The one source that counts as organic. */
export const ORGANIC_SOURCE = "web";

export const VIEWPORTS = Object.freeze(["narrow", "wide"]);

/**
 * The locales the board serves. Kept in step with app/i18n/index.ts by a test
 * rather than by an import, because this file has to stay loadable by plain
 * node --test and by the Worker.
 */
export const LOCALES = Object.freeze(["en", "es"]);

/** A save is about the feed, not about one event, so it carries this instead of an id. */
export const FEED_EVENT_ID = "__feed__";

/** The closed list. Every row carries exactly these keys. */
export const EVENT_FIELDS = Object.freeze([
  "type",
  "ts",
  "client_id",
  "session_id",
  "locale",
  "event_id",
  "position",
  "ranking",
  "model_version",
  "viewport",
  "source",
]);

/**
 * Fields that must never appear, listed by name only so the rejection can say
 * WHICH one arrived. The closed list above already refuses them; this exists so
 * the failure reads "rejected personal field: ip" rather than "unknown field",
 * which is the difference between noticing a privacy bug and filing a typo.
 */
export const FORBIDDEN_FIELDS = Object.freeze([
  "ip",
  "ip_address",
  "remote_addr",
  "email",
  "name",
  "full_name",
  "user_agent",
  "userAgent",
  "ua",
  "referrer",
  "referer",
  "cookie",
  "phone",
  "address",
  "latitude",
  "longitude",
  "geo",
  "country",
  "city",
  "fingerprint",
]);

/**
 * Caps, and why these numbers.
 *
 * Analytics Engine takes at most 250 data points per Worker invocation, so 50
 * is comfortably inside it and still covers a full board of impressions in one
 * or two beacons. The byte cap is the real defence: it bounds the work a single
 * request can ask for without needing to know anything about who sent it.
 *
 * Rate limiting here is by payload and batch size only. There is deliberately
 * no per-client counter, no ban list and no punishment: the client id is random
 * and rotates, so a limit keyed on it would be both ineffective and the one
 * piece of per-person state this design refuses to keep.
 */
export const MAX_BATCH = 50;
export const MAX_BODY_BYTES = 32 * 1024;

/** How long a client id lives before it is thrown away and a new one generated. */
export const CLIENT_ID_ROTATION_DAYS = 7;

const ID_PATTERN = /^[A-Za-z0-9_-]{16,64}$/;
const EVENT_ID_PATTERN = /^[A-Za-z0-9._:-]{1,80}$/;
const VERSION_PATTERN = /^[A-Za-z0-9._-]{1,40}$/;
/** 2020-09-13, comfortably before this project existed. */
const TS_FLOOR = 1600000000000;
/** How far ahead of the server a client clock may be and still be believed. */
const TS_SKEW_MS = 10 * 60 * 1000;

const fail = (reason) => ({ ok: false, reason });

/**
 * Validate one row, strictly.
 *
 * @param {unknown} row
 * @param {{now?: number, checkClock?: boolean}} [options]
 */
export function validateEvent(row, options = {}) {
  const { now = Date.now(), checkClock = true } = options;
  if (row === null || typeof row !== "object" || Array.isArray(row)) {
    return fail("not an object");
  }
  const keys = Object.keys(row);
  for (const key of keys) {
    if (FORBIDDEN_FIELDS.includes(key)) {
      return fail(`rejected personal field: ${key}`);
    }
    if (!EVENT_FIELDS.includes(key)) {
      return fail(`unknown field: ${key}`);
    }
  }
  for (const field of EVENT_FIELDS) {
    if (!(field in row)) return fail(`missing field: ${field}`);
  }

  if (!EVENT_TYPES.includes(row.type)) return fail(`bad type: ${row.type}`);
  if (typeof row.ts !== "number" || !Number.isInteger(row.ts)) {
    return fail("ts must be an integer millisecond timestamp");
  }
  if (row.ts < TS_FLOOR) return fail("ts is implausibly old");
  if (checkClock && row.ts > now + TS_SKEW_MS) return fail("ts is in the future");
  if (typeof row.client_id !== "string" || !ID_PATTERN.test(row.client_id)) {
    return fail("bad client_id");
  }
  if (typeof row.session_id !== "string" || !ID_PATTERN.test(row.session_id)) {
    return fail("bad session_id");
  }
  if (!LOCALES.includes(row.locale)) return fail(`bad locale: ${row.locale}`);
  if (typeof row.event_id !== "string" || !EVENT_ID_PATTERN.test(row.event_id)) {
    return fail("bad event_id");
  }
  if (
    typeof row.position !== "number" ||
    !Number.isInteger(row.position) ||
    row.position < 0 ||
    row.position > 999
  ) {
    return fail("position must be a 0-based rank under 1000");
  }
  if (!RANKING_LABELS.includes(row.ranking)) return fail(`bad ranking: ${row.ranking}`);
  if (
    row.model_version !== null &&
    (typeof row.model_version !== "string" || !VERSION_PATTERN.test(row.model_version))
  ) {
    return fail("bad model_version");
  }
  if (!VIEWPORTS.includes(row.viewport)) return fail(`bad viewport: ${row.viewport}`);
  if (!SOURCES.includes(row.source)) return fail(`bad source: ${row.source}`);

  // Rebuilt field by field rather than passed through, so nothing that got past
  // the key check by being non-enumerable or inherited can reach the sink.
  return {
    ok: true,
    event: {
      type: row.type,
      ts: row.ts,
      client_id: row.client_id,
      session_id: row.session_id,
      locale: row.locale,
      event_id: row.event_id,
      position: row.position,
      ranking: row.ranking,
      model_version: row.model_version,
      viewport: row.viewport,
      source: row.source,
    },
  };
}

/**
 * Validate a whole posted batch: `{ events: [...] }`, nothing else at the top
 * level either.
 *
 * @param {unknown} body
 */
export function validateBatch(body, options = {}) {
  if (body === null || typeof body !== "object" || Array.isArray(body)) {
    return fail("body must be an object");
  }
  for (const key of Object.keys(body)) {
    if (key !== "events") return fail(`unknown top-level field: ${key}`);
  }
  if (!Array.isArray(body.events)) return fail("events must be an array");
  if (body.events.length === 0) return fail("events is empty");
  if (body.events.length > MAX_BATCH) {
    return fail(`batch of ${body.events.length} exceeds the cap of ${MAX_BATCH}`);
  }
  const events = [];
  for (let i = 0; i < body.events.length; i += 1) {
    const result = validateEvent(body.events[i], options);
    if (!result.ok) return fail(`events[${i}]: ${result.reason}`);
    events.push(result.event);
  }
  return { ok: true, events };
}

// --- Analytics Engine shape ---
//
// One data point per event. The index is the client id: Analytics Engine
// samples and groups by index, and per-client is exactly the grain the
// interleaving credit and the bootstrap need. An index is capped at 96 bytes
// and a client id is 22, so it fits with room to spare.

export const BLOB_COLUMNS = Object.freeze([
  "type",
  "client_id",
  "session_id",
  "locale",
  "event_id",
  "ranking",
  "model_version",
  "viewport",
  "source",
]);

export const DOUBLE_COLUMNS = Object.freeze(["ts", "position"]);

export function toDataPoint(event) {
  return {
    indexes: [event.client_id],
    blobs: [
      event.type,
      event.client_id,
      event.session_id,
      event.locale,
      event.event_id,
      event.ranking,
      event.model_version ?? "",
      event.viewport,
      event.source,
    ],
    doubles: [event.ts, event.position],
  };
}

/** Turn one SQL API row (blob1..blob9, double1..double2) back into an event. */
export function fromQueryRow(row) {
  const at = (prefix, index) => row[`${prefix}${index + 1}`];
  const version = at("blob", BLOB_COLUMNS.indexOf("model_version"));
  return {
    type: at("blob", 0),
    ts: Number(at("double", 0)),
    client_id: at("blob", 1),
    session_id: at("blob", 2),
    locale: at("blob", 3),
    event_id: at("blob", 4),
    position: Number(at("double", 1)),
    ranking: at("blob", 5),
    model_version: version === "" ? null : version,
    viewport: at("blob", 7),
    source: at("blob", 8),
  };
}
